function Ex06() {
  return (
    <div className="w-[500px] h-[200px] overflow-auto p-4 border border-gray-300 rounded">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Est ut molestias alias deleniti vel qui accusantium, voluptatibus nesciunt odit veritatis debitis pariatur incidunt nam illo dolorem quibusdam animi veniam. Tempora!
      Maxime ipsa minus, soluta eaque molestias voluptates quidem animi enim quaerat atque, facere velit exercitationem. Explicabo voluptates recusandae dolorem animi aliquid rem ipsa facilis impedit eaque est, nemo obcaecati delectus?
      Illum, nesciunt reprehenderit nostrum harum necessitatibus numquam possimus a voluptate quia praesentium dolorum porro? Expedita qui architecto voluptatem consequatur debitis dolores eos, recusandae ad molestiae praesentium obcaecati? Quaerat, rerum labore?
      Dolorem error sit exercitationem vitae voluptas sequi deleniti aliquid labore amet corrupti, ducimus, quis asperiores. Fuga quod, ipsa rem odio mollitia id quas repellat, inventore officiis suscipit aliquid minus sunt?
      Animi aliquid aspernatur vel unde veniam minus amet, beatae accusantium! Et soluta dolore quod iure aperiam. Repellendus libero, accusamus obcaecati itaque eum, sapiente laudantium magni voluptatibus maiores, enim doloremque consectetur.
      Cupiditate quia eius eligendi fugit excepturi dicta, quod architecto nisi beatae quidem illum vitae. Ratione cum quae quis quod laboriosam fugit possimus. Saepe ullam dignissimos maiores doloribus dicta animi reiciendis.
      Fuga officiis soluta sed facilis excepturi modi minima fugiat dolorem voluptatum error magnam esse illum nulla eaque dolorum in, dolore perferendis inventore quo incidunt, cumque, repellendus laborum vero necessitatibus! Architecto.
      Veniam sequi reiciendis deserunt voluptate iste laborum perspiciatis harum. Expedita iusto harum minima, soluta perferendis animi, veniam nisi quibusdam, voluptatem voluptate voluptatum possimus. Quo rem est tenetur! Modi, hic incidunt.
      Vero quidem atque fugiat itaque assumenda, voluptates nobis eaque nisi dolorem, molestias, repudiandae aliquid tempora! A quaerat aspernatur ad, beatae fuga similique voluptatum corrupti? Fugiat error officiis eaque explicabo maiores!
      Ad dolore recusandae illum laudantium, asperiores quae ipsum nam obcaecati quasi exercitationem porro repellat sit delectus officiis at? Expedita alias enim et aspernatur minus corrupti dolore reiciendis amet maiores voluptates!
      Pariatur nemo at possimus eos quidem. Provident minus porro deserunt eligendi excepturi deleniti, fuga eos, alias quibusdam, consectetur quam et culpa? Provident dicta quas illum sit, ex dolor suscipit. Blanditiis?
      Beatae corporis animi explicabo perspiciatis quis ex necessitatibus, ut quam, ipsam atque cupiditate, officia assumenda veniam sit optio blanditiis exercitationem unde dolor! Magnam inventore voluptas quisquam. Animi, voluptatem. Eveniet, assumenda?
      Libero non veniam sed iste culpa alias molestias eius id, voluptatem voluptatibus, ullam reiciendis ea voluptates quo ad perspiciatis maiores nihil fuga fugiat commodi a excepturi? Corrupti reiciendis aperiam fugit.
      Reiciendis itaque vitae esse at. Deleniti, vero. Explicabo, officiis rem quis optio corporis impedit officia beatae aspernatur, autem esse tempora consectetur? Eos ea dolorum labore nihil. A dolore natus similique?
      Natus nam, distinctio, facere aperiam rem magnam aliquam quibusdam, dignissimos iure earum adipisci nulla quidem libero quia perspiciatis! Modi incidunt voluptatibus debitis, cupiditate temporibus illum repellendus sunt nisi in labore.
      Obcaecati sint molestiae nisi blanditiis accusamus esse quasi earum cumque harum facere, ea, eveniet, necessitatibus quae impedit placeat hic possimus aliquam. Excepturi minus sequi necessitatibus vero labore repellat et dicta.
      Animi doloremque dolorem ipsa quaerat hic minus nesciunt, omnis vitae quia, quis iure accusamus tempora aperiam rem rerum! Laboriosam dolore impedit illum quo eaque soluta voluptas praesentium doloremque aspernatur eum.
      Nemo incidunt ab, voluptatem esse quod maxime reiciendis iusto deleniti fuga sint hic, repellat autem! Vero quia ipsum adipisci incidunt ratione consectetur sit asperiores esse, expedita, laborum, magni exercitationem quo.
      Fuga ipsam, officiis voluptatibus saepe dolor asperiores explicabo provident vitae accusamus quas ea officia, magnam laudantium vero aperiam, eum blanditiis quia molestiae ab corporis odit voluptates? Illum ea nam quidem!
      Dicta, impedit possimus! Magnam aliquid vitae necessitatibus non, fugit consectetur nemo? Minima maiores eius reiciendis ut ipsum, quis numquam odio eveniet totam quisquam laudantium error laboriosam similique corporis. Mollitia, dolorum.
      Ipsum consectetur veritatis deleniti quo corrupti in repellendus doloribus deserunt eaque. Accusantium, error deleniti officia deserunt saepe ab, voluptatem esse rerum, quos cupiditate impedit. Temporibus vitae tenetur fuga omnis quis?
      Aperiam enim, facilis ipsum culpa officia itaque quasi porro laborum eius. Aperiam necessitatibus ea cumque veniam animi, quaerat nisi hic suscipit maiores reiciendis, eos magnam et, harum distinctio nulla similique?
      Odio magni consectetur animi voluptates similique quisquam error impedit ratione dolorum. Eveniet ab fugit voluptates ducimus, sint quaerat atque animi voluptatum eaque amet officia laboriosam modi in dignissimos ea! At!
      Ipsam laborum saepe iusto amet ipsum necessitatibus veniam, debitis voluptate vero earum consequatur exercitationem nam ut culpa molestiae animi deleniti dignissimos, aut voluptatibus reiciendis labore ullam explicabo. Nobis, corporis provident?
      Unde sunt voluptatum aspernatur pariatur mollitia id! Fugit natus, laboriosam assumenda consectetur error, architecto molestiae veritatis neque molestias, quae dolorem vitae dolore est tenetur ab? Quos ipsam at vel debitis?
      Deleniti voluptate, animi, minus molestiae dolor numquam iste veniam laborum repellendus quaerat et rerum voluptas dicta perspiciatis fugiat laboriosam corrupti consequatur, blanditiis quam illum. Sunt quae odit expedita magni saepe.
      Sed quam earum dolor libero laboriosam nihil eius aspernatur tempora assumenda cumque, molestias temporibus similique veniam. Fugiat itaque consequatur totam, doloremque, omnis asperiores porro magni, nulla facilis vitae obcaecati perferendis?
      Maxime perspiciatis temporibus ipsam dolorum aut saepe officia iure harum, exercitationem ratione! Hic at vitae id quidem repellat veniam, laborum tempore perferendis quaerat ex, quisquam eius dolorum voluptatum quis assumenda.
      Perferendis quaerat quam ab ipsa omnis perspiciatis rerum totam exercitationem accusantium, eveniet similique modi hic, sapiente quasi debitis. Asperiores aliquid ipsum debitis dolor, non vero esse eius rerum cum quia.
      Odio vel enim voluptates repellendus cupiditate libero eaque aspernatur consequatur delectus id fugiat ducimus, recusandae animi ipsam non quasi veritatis nesciunt nam laborum exercitationem deleniti doloremque. Dicta temporibus praesentium quae.
      Pariatur, quo. Odio expedita doloremque cumque enim accusamus temporibus maxime ullam possimus, eum facere nisi? Soluta ipsam eaque, pariatur dolore quibusdam magni doloribus, quasi sapiente nemo, consequatur natus similique inventore?
      Et doloremque at reprehenderit voluptates, perferendis dicta expedita exercitationem quos. Quo minus autem amet, dolorum nesciunt fugiat rem deserunt tempora officiis facere in perspiciatis ipsum odit maxime iste recusandae natus!
      Natus, veritatis. Illo officia pariatur quis beatae aspernatur voluptatum rem labore cumque? Corrupti, repellat iure neque laboriosam a aut esse unde minima aperiam? Rem eligendi enim nisi? Eos, deleniti minus?
      In nihil perspiciatis adipisci similique mollitia eveniet obcaecati eaque saepe alias molestias. Aperiam nesciunt necessitatibus quidem quia quasi facere, et magnam asperiores quam dolore esse debitis ut, autem modi. Modi.
      Ex ipsam quasi fuga mollitia reprehenderit numquam animi incidunt dolorum atque qui aperiam ut beatae, magni iste accusantium amet, nemo voluptas sunt neque maiores error. Itaque a quibusdam consequuntur repellat?
      Provident impedit, minus optio quis adipisci quas nesciunt! Similique, cupiditate! Impedit excepturi cupiditate debitis similique tempora delectus omnis architecto maiores repudiandae dicta quam mollitia nihil dolorum rem, totam quos alias.
      Consequuntur minus deserunt dicta nam et architecto placeat dolores minima deleniti, dolorem doloremque laudantium quibusdam recusandae totam, veritatis dolore, eum odit quo! Vel quaerat cum id velit ducimus, nihil alias?
      Pariatur vel voluptate unde sunt minima perspiciatis! Delectus eum ipsam enim tempora accusantium magni totam quaerat iste nisi architecto atque exercitationem fugit est odit sequi impedit, laudantium doloremque dolorem magnam!
      Officia ex sapiente dolore deserunt? Voluptates voluptatibus quis natus, alias ut reprehenderit? Officiis expedita non adipisci quam exercitationem animi perspiciatis molestias, vero, laboriosam necessitatibus deserunt optio libero nostrum, praesentium repudiandae?
      Minima nemo laborum harum ipsa placeat dolorem ipsam quo doloribus magni eum deleniti quam quis, accusamus perspiciatis facere, reprehenderit earum tempora unde corrupti dignissimos sit. Debitis, rerum nesciunt? Quisquam, debitis!
      Nobis dolores expedita magnam nostrum deleniti tenetur at a eligendi quidem unde temporibus magni ea commodi fuga enim quae, aliquid tempora distinctio est eius sed. Porro provident beatae nesciunt ad!
      Nobis praesentium obcaecati quaerat fugiat, placeat nihil, et eveniet harum eligendi magnam corrupti nostrum nisi nulla tempore incidunt error voluptas iure iusto? Praesentium modi, totam enim voluptatum amet cumque! Architecto.
      Tempore est nostrum quae praesentium nisi laudantium accusantium, cumque ex aperiam, neque ducimus consequatur voluptate quaerat a explicabo! Eaque iure cum sunt quae quasi fuga aliquid eligendi odio labore omnis.
      Architecto necessitatibus ipsum dolores, numquam animi incidunt! Inventore nisi eveniet et dolores quidem dolorum magni, non fugit natus sint beatae cum architecto laudantium tempore eum ad praesentium nemo ea quos!
      Eaque eos maxime molestiae. Voluptate obcaecati nobis sapiente voluptatum suscipit. Ducimus perferendis repellat unde, odio asperiores iure officiis quos ratione commodi cupiditate excepturi aspernatur labore quae similique quis, placeat enim!
      Eum consequuntur perspiciatis quia deserunt maxime ratione rerum, unde sunt reprehenderit dicta nihil non voluptatibus pariatur, modi hic minima, vel optio molestiae atque praesentium! Autem rem at voluptatem voluptas amet.
      Ratione adipisci quod pariatur itaque non sequi. Et architecto nam esse, dicta blanditiis hic vero, ducimus commodi, iste doloribus similique. Modi rem quod ratione repellat iure placeat id voluptatibus magnam?
      Illo suscipit dignissimos obcaecati repellat non culpa, error, aliquid voluptatibus totam earum veritatis nobis et libero quisquam asperiores cum nam quos iste sunt ipsum quasi possimus aut a? Dignissimos, ipsa.
      Numquam sed hic quis dolore dolor culpa nulla delectus aut, perferendis praesentium, quod necessitatibus odio voluptate tempore sapiente ipsam assumenda dicta laboriosam eum aspernatur corporis. Recusandae non consectetur tempore temporibus.
      Architecto sunt eaque, libero hic quod alias. Libero eos minus atque earum sit? Cumque, fugiat suscipit exercitationem laudantium dolores quaerat porro consequatur reprehenderit accusantium reiciendis illo saepe labore laboriosam? Temporibus!
    </div>
  );
}

export default Ex06;
